SearchBayesianSkopt: Config 0 Exception. Config: {'batch_size': 153, 'num_factors': 341, 'learning_rate': 0.041260453984744934} - Exception: Traceback (most recent call last):
  File "..\ParameterTuning\SearchAbstractClass.py", line 362, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "..\ParameterTuning\SearchAbstractClass.py", line 267, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "..\ParameterTuning\SearchAbstractClass.py", line 248, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "..\MatrixFactorization\PyTorch\MF_MSE_PyTorch.py", line 35, in __init__
    super(MF_MSE_PyTorch, self).__init__()
TypeError: __init__() missing 1 required positional argument: 'URM_train'

SearchBayesianSkopt: Config 0 Exception. Config: {'batch_size': 256, 'num_factors': 754, 'learning_rate': 0.005947677961138851} - Exception: Traceback (most recent call last):
  File "..\ParameterTuning\SearchAbstractClass.py", line 362, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "..\ParameterTuning\SearchAbstractClass.py", line 267, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "..\ParameterTuning\SearchAbstractClass.py", line 248, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "..\MatrixFactorization\PyTorch\MF_MSE_PyTorch.py", line 35, in __init__
    super(MF_MSE_PyTorch, self).__init__()
TypeError: __init__() missing 1 required positional argument: 'URM_train'

SearchBayesianSkopt: Config 0 Exception. Config: {'batch_size': 126, 'num_factors': 448, 'learning_rate': 0.04470573357712507} - Exception: Traceback (most recent call last):
  File "..\ParameterTuning\SearchAbstractClass.py", line 362, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "..\ParameterTuning\SearchAbstractClass.py", line 267, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "..\ParameterTuning\SearchAbstractClass.py", line 248, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "..\MatrixFactorization\PyTorch\MF_MSE_PyTorch.py", line 35, in __init__
    super(MF_MSE_PyTorch, self).__init__()
TypeError: __init__() missing 1 required positional argument: 'URM_train'

SearchBayesianSkopt: Config 0 Exception. Config: {'batch_size': 328, 'num_factors': 635, 'learning_rate': 0.04796867684388662} - Exception: Traceback (most recent call last):
  File "..\ParameterTuning\SearchAbstractClass.py", line 362, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "..\ParameterTuning\SearchAbstractClass.py", line 267, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "..\ParameterTuning\SearchAbstractClass.py", line 248, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "..\MatrixFactorization\PyTorch\MF_MSE_PyTorch.py", line 35, in __init__
    super(MF_MSE_PyTorch, self).__init__()
TypeError: __init__() missing 1 required positional argument: 'URM_train'

